# Auto‑generated by generate_analysis
from pathlib import Path
CSV_PATH = Path(r"/Users/zhangran/Desktop/BP@UnitedStates/Code/D2D_Data2Dashboard/dataset/Finance_survey_data.csv")

# Auto‑generated by generate_analysis

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# Load the dataset
CSV_PATH = CSV_PATH
df = pd.read_csv(CSV_PATH)

# Create figures directory if it doesn't exist
Path("figures").mkdir(parents=True, exist_ok=True)

# Plotting functions
def plot_age_distribution(df):
    try:
        plt.figure()
        df['age'].plot(kind='hist', bins=range(20, 40, 2), color='skyblue', edgecolor='black')
        plt.title('Age Distribution')
        plt.xlabel('Age')
        plt.ylabel('Frequency')
        plt.tight_layout()
        plt.savefig('figures/age_distribution.png')
    except (KeyError, ValueError, TypeError) as e:
        print(f"Warning: Could not plot age distribution due to {e}")

def plot_gender_distribution(df):
    try:
        plt.figure()
        df['gender'].value_counts().plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['lightcoral', 'lightskyblue'])
        plt.title('Gender Distribution')
        plt.ylabel('')
        plt.tight_layout()
        plt.savefig('figures/gender_distribution.png')
    except (KeyError, ValueError, TypeError) as e:
        print(f"Warning: Could not plot gender distribution due to {e}")

def plot_investment_preferences(df):
    try:
        plt.figure()
        investment_cols = ['Mutual_Funds', 'Equity_Market', 'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']
        df[investment_cols].mean().plot(kind='bar', color='lightgreen')
        plt.title('Average Investment in Different Avenues')
        plt.xlabel('Investment Avenue')
        plt.ylabel('Average Investment')
        plt.tight_layout()
        plt.savefig('figures/investment_preferences.png')
    except (KeyError, ValueError, TypeError) as e:
        print(f"Warning: Could not plot investment preferences due to {e}")

def plot_investment_monitoring(df):
    try:
        plt.figure()
        df['Invest_Monitor'].value_counts().plot(kind='bar', color='lightblue')
        plt.title('Investment Monitoring Frequency')
        plt.xlabel('Frequency')
        plt.ylabel('Count')
        plt.tight_layout()
        plt.savefig('figures/investment_monitoring.png')
    except (KeyError, ValueError, TypeError) as e:
        print(f"Warning: Could not plot investment monitoring frequency due to {e}")

def plot_expected_returns(df):
    try:
        plt.figure()
        df['Expect'].value_counts().plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['gold', 'lightcoral', 'lightskyblue'])
        plt.title('Expected Returns')
        plt.ylabel('')
        plt.tight_layout()
        plt.savefig('figures/expected_returns.png')
    except (KeyError, ValueError, TypeError) as e:
        print(f"Warning: Could not plot expected returns due to {e}")

# Execute plotting functions
plot_age_distribution(df)
plot_gender_distribution(df)
plot_investment_preferences(df)
plot_investment_monitoring(df)
plot_expected_returns(df)

plt.show()